"""
Artifact integrity tool — generate and verify SHA-256 checksums of the
pipeline's input artifacts.

Why this exists
---------------
The system's results depend on three input artifacts per dataset:

    data/<dataset>/chunks_export.json          (Phase-1 chunking output)
    data/<dataset>/graph/extraction_results.json (Phase-2 Colab GLiNER+REBEL)
    data/<dataset>/questions.json              (benchmark questions)

If a reviewer — or future-you after a re-ingest — works from a *different*
version of any of these files, every downstream number is incomparable,
and nothing in the pipeline would flag the mismatch. This tool closes that
failure mode: it writes a `data/SHA256.txt` manifest and can verify any
working tree against it.

Usage
-----
    # Write the manifest (do this once, when the artifacts are final):
    python verify_artifacts.py generate

    # Verify the current tree against the committed manifest:
    python verify_artifacts.py verify

`verify` exits 0 when every listed artifact matches, 1 otherwise — so it
can be used as a CI / pre-ingest gate.

Scope
-----
Stdlib only. Tracks the input artifacts, not the derived stores (LanceDB /
KuzuDB binaries are large and re-derivable from the inputs; their
correctness is checked by the graph-quality invariants, not by checksum).
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

_PROJECT_ROOT = Path(__file__).resolve().parent
_MANIFEST_PATH = _PROJECT_ROOT / "data" / "SHA256.txt"

# Input-artifact glob patterns, relative to the project root. Derived
# stores (vector/, graph/graph_KuzuDB) are intentionally excluded — they
# are re-derivable and large.
_ARTIFACT_PATTERNS: Tuple[str, ...] = (
    "data/*/chunks_export.json",
    "data/*/graph/extraction_results.json",
    "data/*/questions.json",
    "data/*/articles_info.json",
)


def _sha256_file(path: Path, block_size: int = 1 << 20) -> str:
    """Streaming SHA-256 of a file (1 MiB blocks; handles multi-GB files)."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(block_size), b""):
            h.update(block)
    return h.hexdigest()


def _discover_artifacts() -> List[Path]:
    """Return all input artifacts present under the project tree, sorted by
    relative path for a deterministic manifest order."""
    found: List[Path] = []
    for pattern in _ARTIFACT_PATTERNS:
        found.extend(_PROJECT_ROOT.glob(pattern))
    # Sort by POSIX-style relative path so the manifest is OS-independent.
    return sorted(found, key=lambda p: p.relative_to(_PROJECT_ROOT).as_posix())


def _relpath(path: Path) -> str:
    """Project-root-relative POSIX path — stable across Windows / Linux."""
    return path.relative_to(_PROJECT_ROOT).as_posix()


def cmd_generate() -> int:
    """Write data/SHA256.txt for every input artifact found in the tree."""
    artifacts = _discover_artifacts()
    if not artifacts:
        print("No input artifacts found under data/. Nothing to checksum.")
        print(f"Looked for: {', '.join(_ARTIFACT_PATTERNS)}")
        return 1

    lines = [
        "# Edge-RAG input-artifact integrity manifest (SHA-256).",
        "# Generated by verify_artifacts.py. Verify with:",
        "#     python verify_artifacts.py verify",
        "#",
        "# Format: <sha256>  <project-root-relative-path>  <size-bytes>",
        "#",
        "# Covers Phase-1/Phase-2 input artifacts only; the derived",
        "# LanceDB / KuzuDB stores are re-derivable and excluded.",
        "",
    ]
    for path in artifacts:
        digest = _sha256_file(path)
        size = path.stat().st_size
        rel = _relpath(path)
        lines.append(f"{digest}  {rel}  {size}")
        print(f"  {digest[:16]}…  {rel}  ({size / 1024 / 1024:.1f} MB)")

    _MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    _MANIFEST_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nManifest written: {_relpath(_MANIFEST_PATH)} "
          f"({len(artifacts)} artifact(s))")
    return 0


def _parse_manifest() -> List[Tuple[str, str, Optional[int]]]:
    """Parse data/SHA256.txt → list of (sha256, relpath, size_bytes)."""
    if not _MANIFEST_PATH.exists():
        return []
    entries: List[Tuple[str, str, Optional[int]]] = []
    for line in _MANIFEST_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        digest, rel = parts[0], parts[1]
        size = int(parts[2]) if len(parts) >= 3 and parts[2].isdigit() else None
        entries.append((digest, rel, size))
    return entries


def cmd_verify() -> int:
    """Verify the working tree against data/SHA256.txt.

    Exit code 0 = all artifacts match; 1 = any mismatch / missing file /
    missing manifest. Designed to be used as a pre-ingest gate.
    """
    entries = _parse_manifest()
    if not entries:
        print(f"No manifest at {_relpath(_MANIFEST_PATH)} (or it is empty).")
        print("Run `python verify_artifacts.py generate` first.")
        return 1

    ok = True
    for expected_digest, rel, expected_size in entries:
        path = _PROJECT_ROOT / rel
        if not path.exists():
            print(f"  MISSING   {rel}")
            ok = False
            continue
        actual_digest = _sha256_file(path)
        if actual_digest != expected_digest:
            print(f"  MISMATCH  {rel}")
            print(f"            expected {expected_digest}")
            print(f"            actual   {actual_digest}")
            ok = False
            continue
        # Size is informational; the SHA-256 is authoritative.
        size_note = ""
        if expected_size is not None and path.stat().st_size != expected_size:
            size_note = " (size differs but hash matches — manifest stale?)"
        print(f"  OK        {rel}{size_note}")

    if ok:
        print(f"\nAll {len(entries)} artifact(s) verified against the manifest.")
        return 0
    print("\nVERIFICATION FAILED — one or more artifacts differ from the "
          "manifest. Downstream results will not be comparable.")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate / verify SHA-256 checksums of pipeline input "
                    "artifacts (chunks_export.json, extraction_results.json, "
                    "questions.json).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "command", choices=["generate", "verify"],
        help="generate: write data/SHA256.txt. verify: check the tree "
             "against it (exit 1 on any mismatch).",
    )
    args = parser.parse_args()
    if args.command == "generate":
        return cmd_generate()
    return cmd_verify()


if __name__ == "__main__":
    sys.exit(main())
